### PR TITLE
Add Assert.AreAllNotNull / AreAllDistinct / AreAllOfType

### PR DESCRIPTION
**Pull request by Evangelink**
## Summary

Mirror the existing `CollectionAssert.AllItems*` APIs onto `Assert`, producing structured assertion messages per [RFC 012](docs/RFCs/012-Structured-Assertion-Messages.md).

This is the second PR in a series adding collection-style assertions to `Assert`. PR1 (#8234) introduced `Assert.IsSubsetOf` / `IsNotSubsetOf`.

## APIs added

- `Assert.AreAllNotNull(IEnumerable, ...)` and `Assert.AreAllNotNull<T>(IEnumerable<T>, ...)`
- `Assert.AreAllDistinct(IEnumerable, [IEqualityComparer], ...)` and `Assert.AreAllDistinct<T>(IEnumerable<T>, [IEqualityComparer<T>], ...)`
- `Assert.AreAllOfType(Type, IEnumerable, ...)` and `Assert.AreAllOfType<TExpected>(IEnumerable, ...)`

All overloads accept an optional `string? message` and use `[CallerArgumentExpression]` to surface the original source-text in the rendered call site.

## Output format

```text
Assertion failed. Expected all items in collection to be distinct.

duplicates: [5]
collection: [5, 5, 5, 5]

Assert.AreAllDistinct(new[] { 5, 5, 5, 5 })
```

- `null` is reported a single time even when multiple null entries are duplicated.
- Duplicate values are likewise reported once.
- For `AreAllOfType`, the generic call site renders as `Assert.AreAllOfType<TExpected>(...)` (we cannot know the user-typed `T` from `typeof(T).Name`, so we use a stable literal placeholder).

## Tests

Unit tests covering: pass paths, empty collections, null collection (parameter-validation), null comparer, user messages, lazy `IEnumerable<T>`, `T = int?`, derived types, comparer (custom + null-handling), 3+ nulls reported once, repeated-duplicates reported once, both generic and non-generic dispatch.

## Notes for reviewer

- `NonGenericEqualityComparerAdapter` is intentionally duplicated with PR #8234. It will be deduped to a single shared file once both PRs land.
- Three new resx entries plus xlf updates (regenerated, never hand-edited).
- 8 new entries added alphabetically to `PublicAPI.Unshipped.txt`.
- `Build.cmd` is clean (0 warnings, 0 errors) across all TFMs.

Relates to #7956

### CODE REVIEW

**Comment by Evangelink** [comment]
## Review — Dimensions 16–21

---

### Dimension 16 · Naming & Conventions — NIT

**`callSite.Substring(...)` vs range operator**

`BuildCallSiteWithComparerForCollection` uses `callSite.Substring(0, callSite.Length - 1)` instead of the modern C# range syntax. Prefer `callSite[..^1]` for consistency with the rest of the codebase.

```csharp
// current
return string.Concat(callSite.Substring(0, callSite.Length - 1), ", <comparer>)");

// preferred
return string.Concat(callSite[..^1], ", <comparer>)");
```

**`comparer.GetType().Name` as display name**

In `AllItemsAreUnique<T>(..., IEqualityComparer<T>? comparer, ...)` and the non-generic overload, `comparerName` is populated with `comparer.GetType().Name`. For closed-generic comparers (e.g. `EqualityComparer<String>`) this produces a raw CLR name like `EqualityComparer\`1`, not something meaningful to the test author. Consider `comparer.GetType().ToString()` (includes type arguments) or omitting the name entirely when it would render unreadably. This also affects the evidence block shown on failure.

**Everything else** — method names (`*Impl`, `ReportAssert*Failed`), parameter names (`collectionExpression`, `expectedTypeExpression`, `genericTypeArgumentName`), file-scoped namespaces, `#region`/`#endregion` labels — all consistent with existing `Assert` files. ✓

---

### Dimension 17 · Documentation Accuracy — MODERATE

**Null elements are silently skipped in `AllItemsAreInstancesOfType`, but the XML doc says they cause a throw.**

The implementation:

```csharp
if (element is not null && !expectedType.IsInstanceOfType(element))
```

So a `null` element is **not** treated as a failure. The public doc says:

> `<exception cref="AssertFailedException">` Thrown if ... some elements of collection do not inherit from / implement expectedType.

A null element does *not* inherit from `expectedType`, yet it is deliberately excluded. This is a semantic choice (mirroring NUnit/MSTestV1 behavior) but the contract as documented does not mention it. The test file has a comment `// A null element is NOT an instance of any type, so it does not fail this assertion.`, confirming the intentional behaviour — but that intent is missing from the public XML doc.

**Suggested addition** to both the non-generic and generic overloads' `<exception>` block:

```xml
/// Null elements are skipped and do not cause the assertion to fail.
```

(or a dedicated `<remarks>` element).

---

### Dimension 18 · Analyzer & Code Fix Quality

N/A — no changes under `src/Analyzers/`.

---

### Dimension 19 · IPC Wire Compatibility

N/A — no changes to serialization/IPC types in `src/Platform/`.

---

### Dimension 20 · Build Infrastructure & Dependencies — LGTM

* No `eng/Versions.props` or `Directory.Packages.props` changes. ✓  
* No new `<PackageReference>` entries. ✓  
* Three new `.resx` entries (`AllItemsAreNotNullFailedSummary`, `AllItemsAreUniqueFailedSummary`, `AllItemsAreInstancesOfTypeFailedSummary`) — straightforward, correctly placed at end of file. ✓  
* All 14 `.xlf` files regenerated by build (not hand-edited). ✓  
* `PublicAPI.Unshipped.txt` updated with all 8 new signatures; nullability annotations look correct. ✓  

---

### Dimension 21 · Scope & PR Discipline — NIT

**Intentional `NonGenericEqualityComparerAdapter` duplication — no in-code tracking**

The PR description says:

> `NonGenericEqualityComparerAdapter` will be deduplicated once both PRs (#8234 and this one) land.

However there is no `// TODO` comment in the source to make this discoverable when PR #8234 is merged or if the dedup work is ever deprioritised. Recommend adding one:

```csharp
// TODO: deduplicate with the same adapter in Assert.CollectionEquivalence.cs once PR #8234 is merged.
private sealed class NonGenericEqualityComparerAdapter : IEqualityComparer<object?>
```

**Scope** — the PR is tightly focused on the three `AllItems*` APIs plus their resources and tests. No unrelated changes observed. ✓

---

### Summary

| Dim | Verdict | Finding |
|-----|---------|---------|
| 16 | NIT | `callSite[..^1]` over `Substring`; `GetType().Name` gives raw CLR name for generic comparers |
| 17 | MODERATE | Null-element skip behaviour in `AllItemsAreInstancesOfType` is undocumented in public XML docs |
| 18 | N/A | |
| 19 | N/A | |
| 20 | LGTM | |
| 21 | NIT | No in-code `TODO` tracking the planned `NonGenericEqualityComparerAdapter` deduplication |



> Generated by [Expert Code Review (on open)](https://github.com/microsoft/testfx/actions/runs/25882956527/agentic_workflow) for issue #8237 · ● 24.2M · [◷](https://github.com/search?q=repo%3Amicrosoft%2Ftestfx+%22gh-aw-workflow-call-id%3A+microsoft%2Ftestfx%2Freview-on-open.agent%22&type=issues)

**Review by Evangelink — COMMENTED** [review]
## Review: Dimensions 6–10

### Dim 6 — Cross-TFM Compatibility ✅ LGTM

All APIs used (`[CallerArgumentExpression]`, `Cast<>()`, `HashSet<T>(IEqualityComparer<T>)`, collection expressions `[.. collection]`, `StringBuilder`) are already used elsewhere in the codebase across net462/netstandard2.0/net8.0/net9.0. No new TFM gaps introduced.

`#pragma warning disable CS8714` is correct: `HashSet<T>` requires `notnull`, but `T` here can be nullable (e.g. `string?`). This suppression is the right approach rather than constraining the overloads.

---

### Dim 7 — Resource & IDisposable Management ✅ LGTM

`List<T>`, `HashSet<T>`, and `StringBuilder` are not `IDisposable`. No file handles, streams, or other disposable resources created.

---

### Dim 8 — Defensive Coding at Boundaries ✅ LGTM

- **Custom comparer throws**: exceptions from user-supplied `IEqualityComparer`/`IEqualityComparer<T>` propagating out of the assertion is consistent with how `HashSet<T>` behaves everywhere in the framework. Acceptable.
- **`collection is List<T> list ? list : [.. collection]`**: Aliases the original list rather than copying — indices remain stable within the single-threaded execution of the assertion. Non-thread-safe behavior is expected and documented by convention.
- **`collection.Cast<object?>()`**: safe — `CheckParameterNotNull` already guards against null.

---

### Dim 9 — Localization & Resources ✅ LGTM

New `.resx` summary entries (`AllItemsAreNotNullFailedSummary`, `AllItemsAreUniqueFailedSummary`, `AllItemsAreInstancesOfTypeFailedSummary`) are correctly added and used via `FrameworkMessages.*`. `.xlf` files are left for the build to regenerate.

Evidence labels (`"null indices:"`, `"expected type:"`, `"mismatches:"`, `"collection:"`, `"duplicates:"`, `"comparer:"`) and the `"(or derived)"` fragment are hardcoded string literals — but this is **consistent with the established pattern**: `Assert.IsInstanceOfType.cs`, `Assert.IsNull.cs`, `Assert.ThrowsException.cs`, etc. all hardcode the same class of label strings. The `.resx` boundary (summary/user-facing message vs. structural label) is applied uniformly.

The `"index "` prefix inside the mismatch `StringBuilder` is similarly a structural formatting string, consistent with the pattern throughout.

---

### Dim 10 — Test Isolation ✅ LGTM

No static mutable state. Each test creates its input data and assertion action locally. No shared setup that could leak between test cases.

> Generated by [Expert Code Review (on open)](https://github.com/microsoft/testfx/actions/runs/25882956527/agentic_workflow) for issue #8237 · ● 24.2M

File: src/TestFramework/TestFramework/Assertions/Assert.AreAllDistinct.cs [hunk 1]
```diff
@@ -0,0 +1,230 @@
...
+
+        EvidenceBlock evidence = EvidenceBlock.Create()
+            .AddLine("duplicates:", duplicatesText)
+            .AddLine("collection:", collectionText);
+
+        StructuredAssertionMessage structured = new(FrameworkMessages.AreAllDistinctFailedSummary);
+        structured.WithUserMessage(message);
+        structured.WithEvidence(evidence);
+        structured.WithExpectedAndActual(expectedText: null, actualText: collectionText);
+        structured.WithCallSiteExpression(BuildCallSiteWithComparerForCollection("Assert.AreAllDistinct", collectionExpression, hasUserComparer));
```
[the remark this answers is not in the document]
Comment (Evangelink) [reply src/TestFramework/TestFramework/Assertions/Assert.AreAllDistinct.cs]: Fixed in eb1172dad: comparer overload failures now add a `comparer:` evidence line using `comparer.GetType().Name`, so the structured payload keeps the comparer context in both generic and non-generic paths.

File: src/TestFramework/TestFramework/Assertions/Assert.AreAllDistinct.cs [hunk 2]
```diff
@@ -0,0 +1,230 @@
...
+    }
+
+#pragma warning disable CS8714 // The type cannot be used as type parameter in the generic type or method. Nullability of type argument doesn't match 'notnull' constraint.
+    private static void AreAllDistinctImpl<T>(IEnumerable<T> collection, IEqualityComparer<T> comparer, bool hasUserComparer, string? message, string collectionExpression)
+    {
+        List<T> snapshot = collection is List<T> list ? list : [.. collection];
+
+#pragma warning disable IDE0028 // Collection initialization can be simplified - target-typed new with constructor argument is preferred over collection expression here
+        HashSet<T> seen = new(comparer);
+#pragma warning restore IDE0028
```
[the remark this answers is not in the document]
Comment (Evangelink) [reply src/TestFramework/TestFramework/Assertions/Assert.AreAllDistinct.cs]: Fixed in eb1172dad: I removed the unnecessary IDE0028 suppressions and kept the HashSet initializations target-typed (`new(...)`) in both spots.

File: src/TestFramework/TestFramework/PublicAPI/PublicAPI.Unshipped.txt [hunk 3]
```diff
@@ -2,3 +2,11 @@
...
 Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException.ExpectedText.get -> string?
+static Microsoft.VisualStudio.TestTools.UnitTesting.Assert.AreAllDistinct(System.Collections.IEnumerable? collection, System.Collections.IEqualityComparer? comparer, string? message = "", string! collectionExpression = "") -> void
+static Microsoft.VisualStudio.TestTools.UnitTesting.Assert.AreAllDistinct(System.Collections.IEnumerable? collection, string? message = "", string! collectionExpression = "") -> void
+static Microsoft.VisualStudio.TestTools.UnitTesting.Assert.AreAllDistinct<T>(System.Collections.Generic.IEnumerable<T>? collection, System.Collections.Generic.IEqualityComparer<T>? comparer, string? message = "", string! collectionExpression = "") -> void
+static Microsoft.VisualStudio.TestTools.UnitTesting.Assert.AreAllDistinct<T>(System.Collections.Generic.IEnumerable<T>? collection, string? message = "", string! collectionExpression = "") -> void
+static Microsoft.VisualStudio.TestTools.UnitTesting.Assert.AreAllNotNull(System.Collections.IEnumerable? collection, string? message = "", string! collectionExpression = "") -> void
```
[the remark this answers is not in the document]
Comment (Evangelink) [reply src/TestFramework/TestFramework/PublicAPI/PublicAPI.Unshipped.txt:9]: Updated the PR metadata to consistently describe the shipped `Assert.AreAllNotNull` / `AreAllDistinct` / `AreAllOfType` APIs. The title already matched, and the body now matches it as well.

File: src/TestFramework/TestFramework/Assertions/Assert.AreAllOfType.cs [hunk 4]
```diff
@@ -0,0 +1,174 @@
...
+            : $"Assert.AreAllOfType<{genericTypeArgumentName}>";
+
+        string? callSite = genericTypeArgumentName is null
+            ? FormatCallSiteExpression(assertionMethodName, expectedTypeExpression!, collectionExpression, "<expectedType>", "<collection>")
+            : FormatCallSiteExpression(assertionMethodName, collectionExpression, "<collection>");
+
+        StructuredAssertionMessage structured = new(FrameworkMessages.AreAllOfTypeFailedSummary);
+        structured.WithUserMessage(message);
+        structured.WithEvidence(evidence);
+        structured.WithExpectedAndActual(expectedText: null, actualText: collectionText);
```
[the remark this answers is not in the document]
Comment (Evangelink) [reply src/TestFramework/TestFramework/Assertions/Assert.AreAllOfType.cs]: Fixed in eb1172dad: `Assert.AreAllOfType` now populates `ExpectedText` / `assert.expected` with the rendered expected type (`<type> (or derived)`), and I added a payload-focused unit test for it.

File: src/TestFramework/TestFramework/PublicAPI/PublicAPI.Unshipped.txt [hunk 5]
```diff
@@ -2,3 +2,11 @@
...
+static Microsoft.VisualStudio.TestTools.UnitTesting.Assert.AreAllNotNull<T>(System.Collections.Generic.IEnumerable<T>? collection, string? message = "", string! collectionExpression = "") -> void
+static Microsoft.VisualStudio.TestTools.UnitTesting.Assert.AreAllOfType(System.Type? expectedType, System.Collections.IEnumerable? collection, string? message = "", string! expectedTypeExpression = "", string! collectionExpression = "") -> void
+static Microsoft.VisualStudio.TestTools.UnitTesting.Assert.AreAllOfType<TExpected>(System.Collections.IEnumerable? collection, string? message = "", string! collectionExpression = "") -> void
```
[the remark this answers is not in the document]
Comment (Evangelink) [reply src/TestFramework/TestFramework/PublicAPI/PublicAPI.Unshipped.txt:12]: Updated the PR metadata to consistently describe the shipped `Assert.AreAllNotNull` / `AreAllDistinct` / `AreAllOfType` APIs. The title already matched, and the body now matches it as well.

File: src/TestFramework/TestFramework/Assertions/Assert.AreAllDistinct.cs [hunk 6]
```diff
@@ -0,0 +1,231 @@
...
+    // TODO: Deduplicate with the same adapter in Assert.CollectionEquivalence.cs (introduced by PR #8234)
+    // once both PRs have landed.
+    private sealed class NonGenericEqualityComparerAdapter : IEqualityComparer<object?>
+    {
+        private readonly IEqualityComparer _comparer;
+
+        public NonGenericEqualityComparerAdapter(IEqualityComparer comparer)
+            => _comparer = comparer;
+
+        public new bool Equals(object? x, object? y) => _comparer.Equals(x, y);
```
[the remark this answers is not in the document]
Comment (Evangelink) [reply src/TestFramework/TestFramework/Assertions/Assert.AreAllDistinct.cs]: Fixed in eb1172dad: removed the unnecessary `new` modifier from `NonGenericEqualityComparerAdapter.Equals`.

**Comment by Evangelink** [comment]
@copilot resolve the merge conflicts in this pull request

**Comment by Evangelink** [comment]
@copilot+gpt-5.5 fix these build issues

@azure-pipelines
azure-pipelines
/ microsoft.testfx (Build Linux Debug)
src/TestFramework/TestFramework/Assertions/Assert.AreAllDistinct.cs#L132

src/TestFramework/TestFramework/Assertions/Assert.AreAllDistinct.cs(132,9): error IDE0007: (NETCORE_ENGINEERING_TELEMETRY=Build) use 'var' instead of explicit type (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0007)
 [Check failure on line 132 in src/TestFramework/TestFramework/Assertions/Assert.AreAllDistinct.cs](https://github.com/microsoft/testfx/pull/8237/files#annotation_55702165150) 

@azure-pipelines
azure-pipelines
/ microsoft.testfx (Build Linux Debug)
src/TestFramework/TestFramework/Assertions/Assert.AreAllDistinct.cs#L132

src/TestFramework/TestFramework/Assertions/Assert.AreAllDistinct.cs(132,27): error IDE0028: (NETCORE_ENGINEERING_TELEMETRY=Build) Collection initialization can be simplified (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0028)
 [Check failure on line 161 in src/TestFramework/TestFramework/Assertions/Assert.AreAllDistinct.cs](https://github.com/microsoft/testfx/pull/8237/files#annotation_55702165163) 

@azure-pipelines
azure-pipelines
/ microsoft.testfx (Build Linux Debug)
src/TestFramework/TestFramework/Assertions/Assert.AreAllDistinct.cs#L161

src/TestFramework/TestFramework/Assertions/Assert.AreAllDistinct.cs(161,36): error IDE0028: (NETCORE_ENGINEERING_TELEMETRY=Build) Collection initialization can be simplified (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0028)
 [Check failure on line 132 in src/TestFramework/TestFramework/Assertions/Assert.AreAllDistinct.cs](https://github.com/microsoft/testfx/pull/8237/files#annotation_55702165191) 

@azure-pipelines
azure-pipelines
/ microsoft.testfx (Build Linux Debug)
src/TestFramework/TestFramework/Assertions/Assert.AreAllDistinct.cs#L132

src/TestFramework/TestFramework/Assertions/Assert.AreAllDistinct.cs(132,9): error IDE0007: (NETCORE_ENGINEERING_TELEMETRY=Build) use 'var' instead of explicit type (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0007)
 [Check failure on line 132 in src/TestFramework/TestFramework/Assertions/Assert.AreAllDistinct.cs](https://github.com/microsoft/testfx/pull/8237/files#annotation_55702165212) 

@azure-pipelines
azure-pipelines
/ microsoft.testfx (Build Linux Debug)
src/TestFramework/TestFramework/Assertions/Assert.AreAllDistinct.cs#L132

src/TestFramework/TestFramework/Assertions/Assert.AreAllDistinct.cs(132,27): error IDE0028: (NETCORE_ENGINEERING_TELEMETRY=Build) Collection initialization can be simplified (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0028)

**Comment by Evangelink** [comment]
@copilot resolve the merge conflicts in this pull request
