### PR TITLE
Fix array assertion overload ambiguity with older C# versions

### LINKED ISSUE #11022: New Assert.DoesNotContain overloads break compilation if LangVersion=latest is not specified
## Describe the bug

Assert.DoesNotContain overloads introduced in 4.4.0 break compilation when targeting anything but net10.0 if LangVersion=latest is not specified.
The same setup works with 4.3.3.

## Version used

4.4.0

## Steps To Reproduce

1. Create MSTest.Sdk project.
2. Change SDK version to 4.4.0.
3. Change TargetFramework to net8.0.
4. Comment out/delete LangVersion from the project.
5. Build the project.

## Expected behavior
Project builds with no error.

## Actual behavior
Build is broken:
```
error CS0121: The call is ambiguous between the following methods or properties: 'Microsoft.VisualStudio.TestTools.UnitTesting.Assert.DoesNotContain<T>(T, System.Collections.Generic.IEnumerable<T>, string?, string, string)' and 'Microsoft.VisualStudio.TestTools.UnitTesting.Assert.DoesNotContain<T>(T, System.Span<T>, string?, string, string)'
```

[Sample](https://github.com/user-attachments/files/31807750/MSTestAssert.zip) project.

### PR DESCRIPTION
**Pull request by Evangelink**
## Summary

- add exact array overloads across affected `Assert` families so C# 12 consumers, including explicit generic callers, do not encounter ambiguities between `IEnumerable<T>` and span overloads
- add constrained collection forwarders that preserve inferred calls for all concrete `IEnumerable<T>` implementations, including `string`, `ArraySegment<T>`, mixed collection types, and user-defined span-convertible enumerables
- preserve legacy behavior by forwarding compatibility calls to the existing `IEnumerable<T>` implementations
- add a dedicated package-consuming C# 12 compilation oracle with representative calls for every public `Assert` method family, dual-conversion category, collection expressions, and untyped `default` expressions
- require future public overload changes to consider source compatibility in the repository Copilot instructions

Fixes #11022

## Compatibility scope

The complete affected type set supplied by .NET 8–10 is single-dimensional arrays, `string`, and `ArraySegment<T>`. Constrained forwarders also cover inferred calls for arbitrary application-defined enumerable types with implicit span conversions. Exact array overloads cover both inferred and explicit `<T>` calls for the reported/common case. Explicit `<T>` calls for non-array dual-convertible types cannot use the additional inferred collection type parameter and would require an unscalable set of per-type overloads.

## Validation

- package build completed with 0 warnings and 0 errors
- C# 12 `AssertSourceCompatibilityTests` package-consumer oracle passed
- TestFramework tests passed (6,095 tests)
- direct C# 12 probes passed for arrays, strings, `ArraySegment<T>`, `ImmutableArray<T>`, collection expressions, untyped `default`, mixed types, and a custom dual-convertible enumerable
- full Release solution rebuild completed with 0 warnings and 0 errors

### CODE REVIEW

File: test/IntegrationTests/MSTest.Acceptance.IntegrationTests/SdkTests.cs [hunk 1]
```diff
@@ -44,6 +45,11 @@ public class UnitTest1
         [TestMethod]
         public void TestMethod1()
         {
+            int[] values = new[] { 1, 2, 3 };
+            Assert.Contains(1, values);
```
Comment (Youssef1313) [inline test/IntegrationTests/MSTest.Acceptance.IntegrationTests/SdkTests.cs]: Are we sure it's only arrays that cause issues here? We don't want to end up needing to grow the list of overloads if we discover more issues.

It might even be safest to take a breaking change to the very new feature. What was the motivation to add the overloads?

File: test/IntegrationTests/MSTest.Acceptance.IntegrationTests/AssertSourceCompatibilityTests.cs [hunk 2]
```diff
@@ -0,0 +1,401 @@
...
+
+            private static void Throw() => throw new InvalidOperationException();
+
+            private static object ReturnValue() => new object();
+        }
+        """;
+
+    private static readonly Regex PublicAssertMethodRegex = new(
+        @"^static Microsoft\.VisualStudio\.TestTools\.UnitTesting\.Assert\.(?<name>[A-Za-z0-9]+)(?:<|\()",
+        RegexOptions.CultureInvariant);
```
[the remark this answers is not in the document]
Comment (Evangelink) [reply test/IntegrationTests/MSTest.Acceptance.IntegrationTests/AssertSourceCompatibilityTests.cs:545]: Fixed. The PublicAPI regex now accepts attribute prefixes such as `[MSTESTEXP]`, and the C# 12 consumer includes `AddValueFormatter` (both overload forms) and `Scope` call shapes with the experimental diagnostic explicitly scoped by pragmas.

> [!NOTE]
> Auto-replied by the [GitHub Copilot app](https://github.com/github/app).

File: test/IntegrationTests/MSTest.Acceptance.IntegrationTests/SdkTests.cs (hunk 1 above)
Comment (Evangelink) [reply test/IntegrationTests/MSTest.Acceptance.IntegrationTests/SdkTests.cs]: Good call—the initial array-only fix was incomplete. I audited the .NET 8–10 conversion surface and expanded the solution: constrained collection forwarders now cover inferred calls for `string`, `ArraySegment<T>`, and user-defined enumerable-to-span types, while exact array overloads preserve explicit generic array calls. The C# 12 package-consumer test now covers those categories, mixed types, collection expressions, and `default` expressions, so we can keep the new span APIs without a breaking removal.

> [!NOTE]
> Auto-replied by the [GitHub Copilot app](https://github.com/github/app).

File: test/IntegrationTests/MSTest.Acceptance.IntegrationTests/AssertSourceCompatibilityTests.cs [hunk 3]
```diff
@@ -0,0 +1,585 @@
...
+            "TestFramework",
+            "PublicAPI");
+
+        string[] publicApiFiles =
+        [
+            Path.Combine(publicApiDirectory, "PublicAPI.Shipped.txt"),
+            Path.Combine(publicApiDirectory, "PublicAPI.Unshipped.txt"),
+            Path.Combine(publicApiDirectory, "net", "PublicAPI.Shipped.txt"),
+            Path.Combine(publicApiDirectory, "net", "PublicAPI.Unshipped.txt"),
+        ];
```
[the remark this answers is not in the document]
Comment (Evangelink) [reply test/IntegrationTests/MSTest.Acceptance.IntegrationTests/AssertSourceCompatibilityTests.cs:604]: Fixed. The family completeness guard now reads the net9.0 shipped and unshipped baselines in addition to the common and net baselines, so a future net9-only `Assert` family cannot bypass coverage.

> [!NOTE]
> Auto-replied by the [GitHub Copilot app](https://github.com/github/app).

File: test/IntegrationTests/MSTest.Acceptance.IntegrationTests/AssertSourceCompatibilityTests.cs [hunk 4]
```diff
@@ -0,0 +1,585 @@
...
+
+    [TestMethod]
+    public async Task PublicAssertCallShapes_CompileWithCSharp12()
+    {
+        VerifyEveryPublicAssertMethodFamilyHasAConsumerCall();
+
+        string source = ConsumerSource
+            .PatchTargetFrameworks(TargetFrameworks.NetCurrent)
+            .PatchCodeWithReplace("$MSTestVersion$", MSTestVersion);
+        using TestAsset testAsset = await TestAsset.GenerateAssetAsync(AssetName, source);
```
[the remark this answers is not in the document]
Comment (Evangelink) [reply test/IntegrationTests/MSTest.Acceptance.IntegrationTests/AssertSourceCompatibilityTests.cs:562]: Fixed. The C# 12 package-consumer oracle is now parameterized over `TargetFrameworks.NetForDynamicData`, so it compiles both the net8 asset from the reported regression and the asset selected by the current target framework.

> [!NOTE]
> Auto-replied by the [GitHub Copilot app](https://github.com/github/app).

**Review by 0101 — APPROVED** [review]

File: test/IntegrationTests/MSTest.Acceptance.IntegrationTests/AssertSourceCompatibilityTests.cs [hunk 5]
```diff
@@ -0,0 +1,588 @@
...
+            // General constrained collection forwarders have additional generic parameters, so explicit
+            // one-type-argument calls require the exact-array overloads to remain source compatible.
+            internal static void ExplicitGenericArrayCalls(
+                int[] values,
+                int[] other,
+                IEqualityComparer<int> comparer)
+            {
+                Func<int, bool> predicate = value => value > 0;
+
+                Assert.AreAllDistinct<int>(values, comparer);
```
[the remark this answers is not in the document]
Comment (Evangelink) [reply test/IntegrationTests/MSTest.Acceptance.IntegrationTests/AssertSourceCompatibilityTests.cs:109]: Fixed. The oracle now includes all omitted explicit-generic array and `default!` call shapes, with exact array forwarders and handler support where required. Array-oriented sequence overloads use overload priority so the same APIs remain unambiguous under the repository's preview compiler.

> [!NOTE]
> Auto-replied by the [GitHub Copilot app](https://github.com/github/app).

File: test/IntegrationTests/MSTest.Acceptance.IntegrationTests/AssertSourceCompatibilityTests.cs [hunk 6]
```diff
@@ -0,0 +1,588 @@
...
+
+        string source = ConsumerSource
+            .PatchTargetFrameworks(targetFramework)
+            .PatchCodeWithReplace("$MSTestVersion$", MSTestVersion);
+        using TestAsset testAsset = await TestAsset.GenerateAssetAsync(AssetName, source);
+
+        DotnetMuxerResult result = await DotnetCli.RunAsync(
+            $"build -c Release {testAsset.TargetAssetPath}",
+            workingDirectory: testAsset.TargetAssetPath,
+            cancellationToken: TestContext.CancellationToken);
```
[the remark this answers is not in the document]
Comment (Evangelink) [reply test/IntegrationTests/MSTest.Acceptance.IntegrationTests/AssertSourceCompatibilityTests.cs:574]: Fixed. Each generated consumer now restores through an asset-local `.nuget-packages` directory passed via `NUGET_PACKAGES`, so parallel rows always compile against the freshly packed development package rather than a stale global-cache copy.

> [!NOTE]
> Auto-replied by the [GitHub Copilot app](https://github.com/github/app).

File: src/TestFramework/TestFramework/Assertions/Assert.ContainsAll.cs [hunk 7]
```diff
@@ -184,6 +184,82 @@ public static void ContainsAll([NotNull] IEnumerable? expected, [NotNull] IEnume
 
     #region ContainsAll span/memory
 
+    /// <summary>
+    /// Tests whether the specified array contains every element of <paramref name="expected"/>.
```
[the remark this answers is not in the document]
Comment (Evangelink) [reply src/TestFramework/TestFramework/Assertions/Assert.ContainsAll.cs]: Fixed. The summary now explicitly states that `collection` contains every element of the `expected` array, matching the assertion direction and existing API documentation.

> [!NOTE]
> Auto-replied by the [GitHub Copilot app](https://github.com/github/app).

File: src/TestFramework/TestFramework/Assertions/Assert.DoesNotContainAll.cs [hunk 8]
```diff
@@ -179,6 +179,82 @@ public static void DoesNotContainAll([NotNull] IEnumerable? notExpected, [NotNul
 
     #region DoesNotContainAll span/memory
 
+    /// <summary>
+    /// Tests whether the specified array does not contain every element of <paramref name="notExpected"/>.
```
[the remark this answers is not in the document]
Comment (Evangelink) [reply src/TestFramework/TestFramework/Assertions/Assert.DoesNotContainAll.cs]: Fixed. The summary now explicitly states that `collection` does not contain every element of the `notExpected` array, so IntelliSense accurately describes the assertion direction.

> [!NOTE]
> Auto-replied by the [GitHub Copilot app](https://github.com/github/app).

File: test/IntegrationTests/MSTest.Acceptance.IntegrationTests/AssertSourceCompatibilityTests.cs [hunk 9]
```diff
@@ -576,6 +576,16 @@ public async Task PublicAssertCallShapes_CompileWithCSharp12(string targetFramew
         result.AssertExitCodeIs(0);
     }
 
+    private static IEnumerable<object[]> GetSourceCompatibilityTargetFrameworks()
+    {
+        yield return [TargetFrameworks.NetCurrent];
+
+        if (TargetFrameworks.NetCurrent != "net8.0")
```
Comment (Youssef1313) [inline test/IntegrationTests/MSTest.Acceptance.IntegrationTests/AssertSourceCompatibilityTests.cs]: This is always true.

File: test/IntegrationTests/MSTest.Acceptance.IntegrationTests/AssertSourceCompatibilityTests.cs [hunk 10]
```diff
@@ -576,6 +576,16 @@ public async Task PublicAssertCallShapes_CompileWithCSharp12(string targetFramew
...
+        {
+            yield return ["net8.0"];
```
Comment (Youssef1313) [inline test/IntegrationTests/MSTest.Acceptance.IntegrationTests/AssertSourceCompatibilityTests.cs]: It's already going out of support in about two months. I doubt it's important test in this case.

Comment (Evangelink) [reply test/IntegrationTests/MSTest.Acceptance.IntegrationTests/AssertSourceCompatibilityTests.cs]: I kept the net8 row because this regression was reported specifically for a net8 consumer, and it is the only row that compiles the distinct net8 package asset; the current-target row selects the net9 asset. This can be removed with the net8 asset when support is dropped.

> [!NOTE]
> Auto-replied by the [GitHub Copilot app](https://github.com/github/app).

File: test/IntegrationTests/MSTest.Acceptance.IntegrationTests/AssertSourceCompatibilityTests.cs (hunk 9 above)
Comment (Evangelink) [reply test/IntegrationTests/MSTest.Acceptance.IntegrationTests/AssertSourceCompatibilityTests.cs]: Agreed. `NetCurrent` cannot become net8, so I removed the unnecessary condition and now yield the two target rows directly.

> [!NOTE]
> Auto-replied by the [GitHub Copilot app](https://github.com/github/app).
